name: megan_life
description: Megan Life 4.1 Real Assistant Android.
version: 4.1.0+41
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  health: ^11.1.0
  share_plus: ^10.0.2

flutter:
  uses-material-design: true
